# Use postgres/example user/password credentials
version: '3.1'
services:
  db:
    image: postgres
    restart: always
    networks:
      - calendso
    volumes:
      - database-data:/var/lib/postgresql/data/
    env_file: .env
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: calendso
      POSTGRES_HOST_AUTH_METHOD: trust
  calendso:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BASE_URL=${BASE_URL}
        - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
    image: calendso:2.1
    restart: always
    networks:
      - calendso
    ports:
      - 3000:3000
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/calendso?schema=public
    depends_on:
      - db
# Optional use of Prisma Studio. In production, comment out or remove the section below to prevent unwanted access to your database.
  studio:
    image: calendso:2.1
    restart: always
    networks:
      - calendso
    ports:
      - 5555:5555
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/calendso?schema=public
    depends_on:
      - db
    command:
      - npx
      - prisma
      - studio
# END SECTION: Optional use of Prisma Studio.
networks:
  calendso:
    external: false
volumes:
  database-data:
